'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const buildScript = fs.readFileSync(path.join(root, 'build-server-package.ps1'), 'utf8');
assert.doesNotMatch(buildScript, /macos|macOS|mac-distribution|collect-macos/i);
assert.doesNotMatch(fs.readFileSync(path.join(root, 'server-standalone.js'), 'utf8'), /macos|macOS|mac-distribution/i);
assert.match(buildScript, /SyncWatch-Android-v\$version-universal\.apk/);
console.log('standalone server package Windows/Android contract passed.');
